#pragma once
static const char SMARTSNAP_OTA_PUBLIC_KEY[] PROGMEM = R"KEY(-----BEGIN PUBLIC KEY-----
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxrafKnZD/g7IkZxTWehJ
mqHI8xkG5KwWETIE63TsyNndfh+SHJFUlR//wYOr8TYJ/sOZam/+63Jwm/IjxbO7
SQMOM9jRCNJmOSXSTTTsItkspjA5PmUinQRCy2xLolqIQSbRhj6PDjf+OJ+4DYeI
qcV9iPSnSvAQMfgNVunWrhPSCwp7w81A8DI50oLUBu0dDhkSstmmmwdJZYR5uKhm
Gffuuo4JY/O6X2ewu0BwTR1TTyw48uML9YxRq6pHi2ZQTB5jPhekzqew/8vKBvle
Au7a7GA1b1NsQVt0IJhZJtttQO3ImaIXjcMO5Xvqaf8VgFk4mJogyG1Ymmud9eTz
4wIDAQAB
-----END PUBLIC KEY-----
)KEY";
